version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: anpoliakov
      POSTGRES_PASSWORD: anpoliakov
      POSTGRES_DB: monitoring_service
    ports:
      - "5444:5432"
    #volume дописать